public class Clock{
    public static void main (String[] args){
        Clock kitchenclock = new Clock();
        Clock bedroomclock = new Clock();
        System.out.println(kitchenclock. toString());
        System.out.println(bedroomclock. toString());
        
    }
}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          